spring.application.name=rewards

# Enable the H2 Console
spring.h2.console.enabled=true
# Optional: Change the path (default is /h2-console)
spring.h2.console.path=/h2-db

# Configure the DataSource (In-Memory)
spring.datasource.url=jdbc:h2:mem:rewardsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create-drop

# Show SQL queries in the logs for debugging
spring.jpa.show-sql=true

